version: "3.9"
services:
  service:
    build: .
    ports:
      - "49835:49835"
    volumes: 
      - appdata:/root/.aspnet/DataProtection-Keys
  presentation:
    build: ./ParkBee.Assessment.Peresentation/
    ports: 
      - "4200:80"
volumes:
  appdata: